### ISSUE TITLE
How can add a Rate-Limit when extend the class

### ISSUE THREAD

**Issue by iCueto** [sirupsen/airrecord#24] opened 2018-07-25 01:32 UTC
How add a backoff when I inherit the class?

In the documentation show how made it calling the Class ```Airrecord::Table```, but How I can use when I made Class inherit that ```Airrecord::Table```

Using ```self``` don't work, only give the error: Faraday: You can't set a middleware after call a request.

Any Idea? Thank you very much!!!

**Comment by jfrux** [comment] 2018-07-25 11:54
Okay so you should be extending Airrecord not Airtable.

Here is an example of one I've added...

```ruby
class AirtableBase < Airrecord::Table
    def my_method
      # do something for all of my airtables.
    end
  end
```

**Comment by jfrux** [comment] 2018-07-25 14:29
I’m sorry, I misunderstood your question.
This is a duplicate of #7 I believe.

**Comment by iCueto** [comment] 2018-07-25 14:35
That don't  have any answer and is mark as enhancement. Also I was looking for something similar and I've found a Rejected Pull Request, that solved the problem, but is not accepted because is not optional for Airtable Enterprise Plan.

**Comment by jfrux** [comment] 2018-07-25 14:36
Unfortunately I don’t have an answer… I misunderstood you initially.
Sounds like the maintainer is not currently working on this anymore right now but who knows.

Wish I could offer you more help... :-/

**Comment by iCueto** [comment] 2018-07-25 14:42
Is very sad (that the creator is not currently working on this fabulous library).

Anyway, Thank you!

PD: Sorry for my bad english.

**Comment by jfrux** [comment] 2018-07-25 14:43
No apologies needed.  It’s not sad, I’m sure they just don’t require the features you’re requiring so it doesn’t really need to be done.

If you are interested, I think it should be fairly easy to implement this in a fork and do your own PR.

Also I’d try contacting to see if maybe you can get access to begin maintaining it for future versions.

**Comment by sirupsen** [comment] 2018-11-04 09:51
Ugh yes, Faraday deprecated the API. I'm happy to accept a PR upstream that solves this problem. The easiest way is probably just to have a flag for Airrecord where it includes the middleware when the class is created. Open to it!

**Comment by sirupsen** [comment] 2018-11-11 12:50
Tracking this in https://github.com/sirupsen/airrecord/pull/39

**Closed by sirupsen** 2018-11-11 12:50 UTC
